version: '3.1'

services:

  redmine:
    image: redmine
    restart: always
    ports:
      - 8020:3000
    depends_on:
      - db
    environment:
      REDMINE_DB_MARIADB: db
      REDMINE_DB_PASSWORD: example
      REDMINE_SECRET_KEY_BASE: supersecretkey
    volumes:
      - ./config.rb:/usr/src/redmine/config/environment.rb
      # - ./config.ru:/usr/src/redmine/config.ru

  db:
    image: mariadb:11.2
    restart: always
    environment:
      - MARIADB_USER=redmine
      - MARIADB_PASSWORD=example
      - MARIADB_DATABASE=redmine
      - MARIADB_RANDOM_ROOT_PASSWORD=1
      - MARIADB_AUTO_UPGRADE=1
    volumes:
     - ./mariadb:/var/lib/mysql
